// <auto-generated />
using System;
using Driver.web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Driver.web.Migrations
{
    [DbContext(typeof(Datacontext))]
    [Migration("20210529055149_MigrationInitial")]
    partial class MigrationInitial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Driver.web.Data.Entities.MDRol", b =>
                {
                    b.Property<int>("Idrol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Rol_UsuarioIdrol_usua")
                        .HasColumnType("int");

                    b.Property<int>("id_sede")
                        .HasColumnType("int");

                    b.Property<string>("rol_desc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Idrol");

                    b.HasIndex("Rol_UsuarioIdrol_usua");

                    b.ToTable("Rol");
                });

            modelBuilder.Entity("Driver.web.Data.Entities.MDRol_Usuario", b =>
                {
                    b.Property<int>("Idrol_usua")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<int>("Idrol")
                        .HasColumnType("int");

                    b.Property<int>("id_sede")
                        .HasColumnType("int");

                    b.HasKey("Idrol_usua");

                    b.ToTable("Rol_Usuario");
                });

            modelBuilder.Entity("Driver.web.Data.Entities.MDUsuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Rol_UsuarioIdrol_usua")
                        .HasColumnType("int");

                    b.Property<string>("Usua_Hash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Usua_act")
                        .HasColumnType("bit");

                    b.Property<string>("Usua_apellidos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Usua_email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Usua_imagen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Usua_nombres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Usua_pass")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Usua_user")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Rol_UsuarioIdrol_usua");

                    b.HasIndex("Usua_user")
                        .IsUnique();

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("Driver.web.Data.Entities.MDRol", b =>
                {
                    b.HasOne("Driver.web.Data.Entities.MDRol_Usuario", "Rol_Usuario")
                        .WithMany()
                        .HasForeignKey("Rol_UsuarioIdrol_usua");

                    b.Navigation("Rol_Usuario");
                });

            modelBuilder.Entity("Driver.web.Data.Entities.MDUsuario", b =>
                {
                    b.HasOne("Driver.web.Data.Entities.MDRol_Usuario", "Rol_Usuario")
                        .WithMany()
                        .HasForeignKey("Rol_UsuarioIdrol_usua");

                    b.Navigation("Rol_Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
